improve 'hostname' compatibility
rootless-containers/usernetes pull request #224
Opened 2021-05-14 07:16 UTC by Silvanoc

The original 'hostname' command provided by the project 'net-tools'
doesn't support the option '-I' (see last comment of the 'net-tools'
webpage).

Those tools invoking 'hostname' with the option '-I' (rootlesskit.sh
and cfssl.sh at the time of this writing) work on distros using a
version of 'hostname' supporting '-I' (basically Debian and RedHat
derivatives) out of the box. But it doesn't on those using the original
'hostname' (like ArchLinux and derivatives).

This patch adds support for ArchLinux and derivatives using the default
distro 'hostname' by falling back to using '-i' on those systems not
supporting the option '-I'. The only difference is that it depends on
name resolution (see [2] for the documentation of the option '-I').

[1] https://net-tools.sourceforge.io/
[2] https://linux.die.net/man/1/hostname

Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>

Closes #223

2021-05-14 14:35 UTC, AkihiroSuda approved these changes
Thanks

2021-05-20 07:31 UTC, AkihiroSuda requested changes
CI failing

2021-05-21 11:59 UTC, Silvanoc commented
Can I somehow get more information about the failing check? I'm having difficulties to understand what went wrong. Is it possible to retrigger the checks to avoid temporary issues?

BTW I've tested the patch on ArchLinux and Debian.

2021-05-21 12:13 UTC, Silvanoc commented
Could [this](https://github.com/rootless-containers/usernetes/pull/224/checks?check_run_id=2622228568#step:7:52) be what's failing? If yes, then I have no idea how my patch could have triggered it...

2021-05-21 12:28 UTC, Silvanoc commented
Got it! I somehow messed up the files permissions.

2021-05-22 13:45 UTC, Silvanoc commented
All checks are passing now. It should be ready to merge.

I had accidentally removed the executable flag from the two files I had modified.

I also had to mute stdout and stderr when verifying the availability of the flag `-I. What was anyway meaningful to avoid a cluttered up output. That part of the code is also now more elegant.

2021-05-22 13:55 UTC, AkihiroSuda approved these changes
Thanks

2021-05-22 13:56 UTC, merged